### ISSUE TITLE
Measured tip temperature stays at ~26C despite full power blown in the heater

### ISSUE THREAD

**Issue by m-kozlowski** [sparkybg/UniSolder-5.2#10]
Problem appeared in 2020.06 release, but I'm observing it in current master as well.
The tip quickly goes red, but the controller still thinks it's at room temperature.
It works correctly after reverting back to previous release.
Using C210, MX564F128H.

**Comment by m-kozlowski** [comment]
narrowed it down to commit 3fd78cdac4acf813e8b50ac502d377aff723f95a

**Comment by sparkybg** [comment]
It now works. Tested!
