### ISSUE TITLE
5.2C Schematics show 100nF power decoupling cap outputs ganged together

### ISSUE THREAD

**Issue by rokkoyama** [sparkybg/UniSolder-5.2#12]
5.2C front schematic shows 100nF power decoupling cap ganged together downstream, across all of the uC inputs.

PCB shows caps dedicated to each of the pins 10, 19, 26, 38, 57 as would be expected.

Please confirm the schem should be corrected.

**Comment by sparkybg** [comment]
Schematic is correct. There is no need for capacitors to be dedicated on schematic also. They are between Vdd and Gnd and this is corretcly shown on chematics.
