### ISSUE TITLE
C245 Thermocouple calibration (not an issue, the forum doesn't work)

### ISSUE THREAD

**Issue by alpemwarrior** [sparkybg/UniSolder-5.2#13]
Hi there, I'm working on a controller of my own (nothing wrong with unisolder, just too complex for me :) ) and wanted to find what exact thermocouple type is on the C245 series cartridges by JBC. I've done quite a bit of research I finally think it's a so-called type M thermocouple (Ni/Mo - Ni/Co), because at the temperature these cartridges were calibrated at (I understand that would be 183ºC for 63/37 solder) this type of thermocouple has the exact same EMF output as unisolder would expect (using 43,5uV/ºC). It would also fit all the descriptions of the materials I've been able to find. Attached is a graph I made for reference.

![tc](https://user-images.githubusercontent.com/68869769/206292490-29d50d77-ebb2-4873-a4c4-c27397121818.png)

**What I wanted to ask**, seeing that you worked with both pure lead and 63/37, is whether the TC output was observed to be strictly linear or if when calibrated at 183 °C the station displayed a temperature higher than real at 327,5 °C (melting lead). 

I'm happy to close this issue if deemed inappropriate, thanks in advance.

**Comment by labjr61** [comment]
> Hi there, I'm working on a controller of my own (nothing wrong with unisolder, just too complex for me :) ) and wanted to find what exact thermocouple type is on the C245 series cartridges by JBC. I've done quite a bit of research I finally think it's a so-called type M thermocouple (Ni/Mo - Ni/Co), because at the temperature these cartridges were calibrated at (I understand that would be 183ºC for 63/37 solder) this type of thermocouple has the exact same EMF output as unisolder would expect (using 43,5uV/ºC). It would also fit all the descriptions of the materials I've been able to find. Attached is a graph I made for reference.
> 
> ![tc](https://user-images.githubusercontent.com/68869769/206292490-29d50d77-ebb2-4873-a4c4-c27397121818.png)
> 
> **What I wanted to ask**, seeing that you worked with both pure lead and 63/37, is whether the TC output was observed to be strictly linear or if when calibrated at 183 °C the station displayed a temperature higher than real at 327,5 °C (melting lead).
> 
> I'm happy to close this issue if deemed inappropriate, thanks in advance.

Interesting. Let us know if you start a new thread elsewhere.

**Comment by alpemwarrior** [comment]
Dear lord am I dumb. Thanks a lot for the answer.
