### ISSUE TITLE
 Compilation failed

### ISSUE THREAD

**Issue by SUzhouTaoTao** [sparkybg/UniSolder-5.2#15]
I used mplab-v6.1.5 xc32-v4.35(free)  and the compilation failed. What version do you use?

**Comment by sparkybg** [comment]
You need legacy peripheral libraries in order to compile it. It is distributed separately. It can be downloaded from microchip's web site.

**Comment by sparkybg** [comment]
And, there is a compiled HEX files in the project folders. You may use them instead.

**Comment by SUzhouTaoTao** [comment]
> 而且，项目文件夹中有一个编译的 HEX 文件。您可以改用它们。


This gives me some direction. Thanks for answering the question

**Comment by SUzhouTaoTao** [comment]
> You need the Legacy Peripheral Libraries in order to compile it. It is distributed separately. It can be downloaded from microchip's web site.

I got it done, thanks
