### ISSUE TITLE
OLED Internal charge pump setup swaped for SSH1106 and SSD1306

### ISSUE THREAD

**Issue by Janesak1977** [sparkybg/UniSolder-5.2#5]
**This is actual  code**
if(DisplaySetup.SH1106){
        PreUpdateBuff.PreRowUpdate.ColLow = 2; //SSH1106 is 131x64 - shift right by 2
        mcuSPISendByte(0x8D); //charge pump control       
        mcuSPISendByte(DisplaySetup.InternalChargePump ? 0x14 : 0x10);        
    }
    else{
        PreUpdateBuff.PreRowUpdate.ColLow = 0; //SSD1306 is 128x64 - no need to shift
        mcuSPISendByte(0xAD); //charge pump control       
        mcuSPISendByte(DisplaySetup.InternalChargePump ? 0x8B : 0x8A);
    }

**Correct is**
if(DisplaySetup.SH1106){
        PreUpdateBuff.PreRowUpdate.ColLow = 2; //SSH1106 is 131x64 - shift right by 2
        mcuSPISendByte(0xAD); //charge pump control       
        mcuSPISendByte(DisplaySetup.InternalChargePump ? 0x8B : 0x8A);     
    }
    else{
        PreUpdateBuff.PreRowUpdate.ColLow = 0; //SSD1306 is 128x64 - no need to shift
        mcuSPISendByte(0x8D); //charge pump control
        mcuSPISendByte(DisplaySetup.InternalChargePump ? 0x14 : 0x10); 
    }

**Comment by sparkybg** [comment]
Yes, it seems so. Correct it then, and open a pull request. It must be the same in the bootloader also. I won't have the time soon.
