### ISSUE TITLE
After I burn the firmware, the screen shows 45

### ISSUE THREAD

**Issue by ws786873** [sparkybg/UniSolder-5.2#8]
Is this a fault code? Do you have the corresponding documents?

**Comment by robpneu** [comment]
Error 45 is the I2C communication not working, usually with the EEPROM chip (U8). It is likely dead. [Forum posts with the same issue](http://dangerousprototypes.com/forum/index.php?topic=7218.msg72881#msg72881) and [confirmation that it was the resolution](http://dangerousprototypes.com/forum/index.php?topic=7218.msg72898#msg72898)

**Comment by ws786873** [comment]
thank you~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rob ***@***.***&gt;; 
发送时间: 2021年4月22日(星期四) 凌晨0:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sparkybg/UniSolder-5.2] After I burn the firmware, the screen shows 45 (#8)





 
Error 45 is the I2C communication not working, usually with the EEPROM chip (U8). It is likely dead. Forum posts with the same issue and confirmation that it was the resolution

**Comment by ws786873** [comment]
Today, after I confirmed that there is no problem with the connector I made, it should be the problem with the U8. Then I found that 21 would be displayed before 45. What's the problem？

**Comment by sparkybg** [comment]
45 is right before it tries to read the parameters from EEPROM. So, it is most likely that your EEPROM chip is malfunctioning.

**Comment by ws786873** [comment]
Hi~i replace the U8,but display 21 then 45

**Comment by sparkybg** [comment]
Then something else on the I2C line is malfunctioning.

Check if the pull-up resistors are located correctly.

**Comment by ws786873** [comment]
your meaning is R27 and R28?,They are ok.
